Repository 103cuong/kovid_bot, pull requests merged in 2020-04, with the labels that each got.

#1 Add skeleton
  package.json
  src/countries.json
  src/index.ts
  tsconfig.json
  yarn.lock
Labels: enhancement

#2 Complete UI & features
  src/index.ts
Labels: enhancement

#3 Deploy to Heroku
  heroku.yml
  src/index.ts
Labels: enhancement

#4 Update country usage
  src/countries.json
  src/index.ts
Labels: enhancement

#6 Update README
  README.md
Labels: documentation

#7 Handle 404 command
  package.json
  src/images/not_found.jpg
  src/index.ts
  yarn.lock
Labels: enhancement

#8 Update README.md
  README.md
Labels: documentation

#9 Fix "yarn build" command
  package.json
Labels: bug
